package com.example.g12tree;

import java.sql.SQLException;
import java.util.Calendar;
import java.util.HashMap;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.data.fieldgroup.PropertyId;
import com.vaadin.data.util.sqlcontainer.RowId;
import com.vaadin.data.util.sqlcontainer.SQLContainer;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Label;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

public class EditPage extends Window implements View {

	private AbsoluteLayout mainLayout;
	private TabSheet addTabSheet;
	private AbsoluteLayout absoluteLayout_3;
	private OptionGroup optionGroup_2;
	private Label label_15;
	private Label updateEditLabel;
	private TextField memberId_textBox;
	private CheckBox checkBox_3;
	private CheckBox checkBox_2;
	private Label label_5;
	private ComboBox comboBox_3;
	private Button saveEdit;
	private TextField textField_6;
	private TextField textField_5;
	private TextField textField_4;
	private Label label_13;
	private Label label_12;
	private TextField textField_3;
	private TextField textField_2;

	@PropertyId("memberFirstName")
	private TextField textField_1;
	private Label label_11;
	private Label label_10;
	private Label label_9;
	private Label label_8;
	private Label label_7;
	private ComboBox comboBox_2;
	private Label label_6;
	private AbsoluteLayout addDiscipleTab;
	private OptionGroup optionGroup_1;
	private Label label_14;
	private Label updateAddLabel;
	private Button saveButton;
	private TextField Nickname;
	private Label label_4;
	private TextField LastnameInputBox;
	private Label label_3;
	private TextField firsnameInputBox;
	private Label label_2;
	private ComboBox comboBox_1;
	private Label label_1;
	private VerticalLayout vLayout2 = new VerticalLayout();
	private FieldGroup fieldGroup;
	private SQLContainer sqlContainer;
	private Object id;

	public EditPage(HashMap<String, SQLContainer> container, Object target) {
		id = target;
		sqlContainer = container.get("memberinfo");
		buildMainLayout();
		initValues(target, container);
		setContent(mainLayout);
		setWidth("350px");
		setHeight("450px");
		setModal(true);
		setCaption("EDIT INFORMATION");
	}

	private void initValues(Object target,
			HashMap<String, SQLContainer> container) {
		SQLContainer memberContainer = container.get("memberinfo");

		setEditFirsnameInputBox(memberContainer
				.getContainerProperty(target, "memberFirstName").getValue()
				.toString());
		setEditLastnameInputBox(memberContainer
				.getContainerProperty(target, "memberLastName").getValue()
				.toString());
		setEditNicknameInputBox(memberContainer
				.getContainerProperty(target, "memberNickname").getValue()
				.toString());
		setClassfication(memberContainer
				.getContainerProperty(target, "memberClass").getValue()
				.toString());
		setLDICheckBox(memberContainer
				.getContainerProperty(target, "ldiGraduate").getValue()
				.toString().equals("1") ? true : false);
		setSolCheckBox(memberContainer
				.getContainerProperty(target, "solGraduate").getValue()
				.toString().equals("1") ? true : false);
	}

	private void buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// addTabSheet
		addTabSheet = buildAddTabSheet();
		mainLayout.addComponent(addTabSheet, "top:0.0px;left:0.0px;");

	}

	@AutoGenerated
	private TabSheet buildAddTabSheet() {
		// common part: create layout
		addTabSheet = new TabSheet();
		addTabSheet.setCaption("Add Disciple");
		addTabSheet.setImmediate(true);
		addTabSheet.setWidth("360px");
		addTabSheet.setHeight("460px");

		// addDiscipleTab

		// absoluteLayout_3
		absoluteLayout_3 = buildAbsoluteLayout_3();
		addTabSheet.addTab(absoluteLayout_3, "Edit Info", null);

		addDiscipleTab = buildAddDiscipleTab();
		addTabSheet.addTab(addDiscipleTab, "Add Disciple", null);

		return addTabSheet;
	}

	@AutoGenerated
	private AbsoluteLayout buildAddDiscipleTab() {
		// common part: create layout
		addDiscipleTab = new AbsoluteLayout();
		addDiscipleTab.setImmediate(false);
		addDiscipleTab.setWidth("100.0%");
		addDiscipleTab.setHeight("100.0%");

		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Leader");
		addDiscipleTab.addComponent(label_1, "top:10.0px;left:9.0px;");

		// comboBox_1
		comboBox_1 = new ComboBox();
		comboBox_1.setImmediate(false);
		comboBox_1.setWidth("-1px");
		comboBox_1.setHeight("-1px");
		comboBox_1.setNullSelectionAllowed(false);
		addDiscipleTab.addComponent(comboBox_1, "top:8.0px;left:79.0px;");

		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Firstname");
		addDiscipleTab.addComponent(label_2, "top:50.0px;left:9.0px;");

		// firsnameInputBox
		firsnameInputBox = new TextField();
		firsnameInputBox.setImmediate(false);
		firsnameInputBox.setWidth("-1px");
		firsnameInputBox.setHeight("-1px");
		addDiscipleTab
				.addComponent(firsnameInputBox, "top:48.0px;left:79.0px;");

		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("-1px");
		label_3.setHeight("-1px");
		label_3.setValue("LastName");
		addDiscipleTab.addComponent(label_3, "top:90.0px;left:7.0px;");

		// LastnameInputBox
		LastnameInputBox = new TextField();
		LastnameInputBox.setImmediate(false);
		LastnameInputBox.setWidth("-1px");
		LastnameInputBox.setHeight("-1px");
		addDiscipleTab
				.addComponent(LastnameInputBox, "top:84.0px;left:79.0px;");

		// label_4
		label_4 = new Label();
		label_4.setImmediate(false);
		label_4.setWidth("-1px");
		label_4.setHeight("-1px");
		label_4.setValue("Nickname");
		addDiscipleTab.addComponent(label_4, "top:130.0px;left:8.0px;");

		// Nickname
		Nickname = new TextField();
		Nickname.setImmediate(false);
		Nickname.setWidth("-1px");
		Nickname.setHeight("-1px");
		addDiscipleTab.addComponent(Nickname, "top:124.0px;left:78.0px;");

		// saveButton
		saveButton = new Button();
		saveButton.setCaption("Save");
		saveButton.setImmediate(true);
		saveButton.setWidth("-1px");
		saveButton.setHeight("-1px");
		saveButton.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				close();
				sqlContainer.getContainerProperty(id, "memberLastName")
						.setValue(getEditLastnameInputBox());
				try {
					sqlContainer.commit();
				} catch (UnsupportedOperationException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}

			}
		});
		addDiscipleTab.addComponent(saveButton, "top:215.0px;left:213.0px;");

		// updateAddLabel
		updateAddLabel = new Label();
		updateAddLabel.setImmediate(false);
		updateAddLabel.setWidth("-1px");
		updateAddLabel.setHeight("-1px");
		updateAddLabel.setValue("");
		addDiscipleTab.addComponent(updateAddLabel, "top:222.0px;left:19.0px;");

		// label_14
		label_14 = new Label();
		label_14.setImmediate(false);
		label_14.setWidth("-1px");
		label_14.setHeight("-1px");
		label_14.setValue("Gender");
		addDiscipleTab.addComponent(label_14, "top:168.0px;left:7.0px;");

		// optionGroup_1
		optionGroup_1 = new OptionGroup();
		optionGroup_1.setImmediate(false);
		optionGroup_1.setWidth("-1px");
		optionGroup_1.setHeight("40px");
		optionGroup_1.addItem("Male");
		optionGroup_1.addItem("Female");
		addDiscipleTab.addComponent(optionGroup_1, "top:168.0px;left:74.0px;");

		return addDiscipleTab;
	}

	private AbsoluteLayout buildAbsoluteLayout_3() {
		// common part: create layout
		absoluteLayout_3 = new AbsoluteLayout();
		absoluteLayout_3.setImmediate(false);
		absoluteLayout_3.setWidth("100.0%");
		absoluteLayout_3.setHeight("100.0%");

		// label_6
		label_6 = new Label();
		label_6.setImmediate(false);
		label_6.setWidth("-1px");
		label_6.setHeight("-1px");
		label_6.setValue("leaderId");
		absoluteLayout_3.addComponent(label_6, "top:8.0px;left:19.0px;");

		// comboBox_2
		comboBox_2 = new ComboBox();
		comboBox_2.setImmediate(false);
		comboBox_2.setWidth("-1px");
		comboBox_2.setHeight("-1px");
		absoluteLayout_3.addComponent(comboBox_2, "top:8.0px;left:101.0px;");

		// label_7
		label_7 = new Label();
		label_7.setImmediate(false);
		label_7.setWidth("-1px");
		label_7.setHeight("-1px");
		label_7.setValue("First Name");
		absoluteLayout_3.addComponent(label_7, "top:36.0px;left:20.0px;");

		// label_8
		label_8 = new Label();
		label_8.setImmediate(false);
		label_8.setWidth("-1px");
		label_8.setHeight("-1px");
		label_8.setValue("Last Name");
		absoluteLayout_3.addComponent(label_8, "top:62.0px;left:20.0px;");

		// label_9
		label_9 = new Label();
		label_9.setImmediate(false);
		label_9.setWidth("-1px");
		label_9.setHeight("-1px");
		label_9.setValue("Nickname");
		absoluteLayout_3.addComponent(label_9, "top:85.0px;left:20.0px;");

		// label_10
		label_10 = new Label();
		label_10.setImmediate(false);
		label_10.setWidth("-1px");
		label_10.setHeight("-1px");
		label_10.setValue("Classification");
		absoluteLayout_3.addComponent(label_10, "top:111.0px;left:20.0px;");

		// label_11
		label_11 = new Label();
		label_11.setImmediate(false);
		label_11.setWidth("-1px");
		label_11.setHeight("-1px");
		label_11.setValue("# Cell Groups");
		absoluteLayout_3.addComponent(label_11, "top:130.0px;left:21.0px;");

		// textField_1
		textField_1 = new TextField();
		textField_1.setImmediate(false);
		textField_1.setWidth("-1px");
		textField_1.setHeight("-1px");
		absoluteLayout_3.addComponent(textField_1, "top:32.0px;left:102.0px;");

		// textField_2
		textField_2 = new TextField();
		textField_2.setImmediate(false);
		textField_2.setWidth("-1px");
		textField_2.setHeight("-1px");
		absoluteLayout_3.addComponent(textField_2, "top:56.0px;left:102.0px;");

		// textField_3
		textField_3 = new TextField();
		textField_3.setImmediate(false);
		textField_3.setWidth("-1px");
		textField_3.setHeight("-1px");
		absoluteLayout_3.addComponent(textField_3, "top:80.0px;left:102.0px;");

		// label_12
		label_12 = new Label();
		label_12.setImmediate(false);
		label_12.setWidth("-1px");
		label_12.setHeight("-1px");
		label_12.setValue("# BS Groups");
		absoluteLayout_3.addComponent(label_12, "top:151.0px;left:20.0px;");

		// label_13
		label_13 = new Label();
		label_13.setImmediate(false);
		label_13.setWidth("-1px");
		label_13.setHeight("-1px");
		label_13.setValue("# of 1 on 1");
		absoluteLayout_3.addComponent(label_13, "top:177.0px;left:21.0px;");

		// textField_4
		textField_4 = new TextField();
		textField_4.setImmediate(false);
		textField_4.setWidth("-1px");
		textField_4.setHeight("-1px");
		absoluteLayout_3.addComponent(textField_4, "top:126.0px;left:102.0px;");

		// textField_5
		textField_5 = new TextField();
		textField_5.setImmediate(false);
		textField_5.setWidth("-1px");
		textField_5.setHeight("-1px");
		absoluteLayout_3.addComponent(textField_5, "top:149.0px;left:102.0px;");

		// textField_6
		textField_6 = new TextField();
		textField_6.setImmediate(false);
		textField_6.setWidth("-1px");
		textField_6.setHeight("-1px");
		absoluteLayout_3.addComponent(textField_6, "top:172.0px;left:102.0px;");

		// saveEdit
		saveEdit = new Button();
		saveEdit.setCaption("Save");
		saveEdit.setImmediate(true);
		saveEdit.setWidth("-1px");
		saveEdit.setHeight("-1px");
		saveEdit.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {

				
				
				
				sqlContainer.getContainerProperty(id, "memberLastName")
						.setValue(getEditLastnameInputBox());
				
				try {
					sqlContainer.commit();
				} catch (UnsupportedOperationException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}

				close();

			}
		});
		absoluteLayout_3.addComponent(saveEdit, "top:301.0px;left:216.0px;");

		// comboBox_3
		comboBox_3 = new ComboBox();
		comboBox_3.setImmediate(false);
		comboBox_3.setWidth("-1px");
		comboBox_3.setHeight("-1px");
		comboBox_3.setNullSelectionAllowed(false);
		comboBox_3.addItem("Follower");
		comboBox_3.addItem("BS Leader");
		comboBox_3.addItem("Cell Leader");
		comboBox_3.addItem("Network Leader");
		comboBox_3.addItem("Elder");
		absoluteLayout_3.addComponent(comboBox_3, "top:104.0px;left:101.0px;");

		// label_5
		label_5 = new Label();
		label_5.setImmediate(false);
		label_5.setWidth("-1px");
		label_5.setHeight("-1px");
		label_5.setValue("Training Attended");
		absoluteLayout_3.addComponent(label_5, "top:198.0px;left:21.0px;");

		// checkBox_2
		checkBox_2 = new CheckBox();
		checkBox_2.setCaption("Leadership Development Institute");
		checkBox_2.setImmediate(false);
		checkBox_2.setWidth("-1px");
		checkBox_2.setHeight("-1px");
		absoluteLayout_3.addComponent(checkBox_2, "top:216.0px;left:101.0px;");

		// checkBox_3
		checkBox_3 = new CheckBox();
		checkBox_3.setCaption("School Of Leaders");
		checkBox_3.setImmediate(false);
		checkBox_3.setWidth("-1px");
		checkBox_3.setHeight("-1px");
		absoluteLayout_3.addComponent(checkBox_3, "top:235.0px;left:102.0px;");

		// memberId_textBox
		memberId_textBox = new TextField();
		memberId_textBox.setEnabled(false);
		memberId_textBox.setImmediate(false);
		memberId_textBox.setWidth("57px");
		memberId_textBox.setHeight("-1px");
		absoluteLayout_3.addComponent(memberId_textBox,
				"top:8.0px;left:282.0px;");

		// updateEditLabel
		updateEditLabel = new Label();
		updateEditLabel.setImmediate(false);
		updateEditLabel.setWidth("-1px");
		updateEditLabel.setHeight("-1px");
		updateEditLabel.setValue("");
		absoluteLayout_3.addComponent(updateEditLabel,
				"top:310.0px;left:19.0px;");

		// label_15
		label_15 = new Label();
		label_15.setImmediate(false);
		label_15.setWidth("-1px");
		label_15.setHeight("-1px");
		label_15.setValue("Gender");
		absoluteLayout_3.addComponent(label_15, "top:254.0px;left:21.0px;");

		// optionGroup_2
		optionGroup_2 = new OptionGroup();
		optionGroup_2.setImmediate(false);
		optionGroup_2.setWidth("97px");
		optionGroup_2.setHeight("100.0%");
		optionGroup_2.addItem("Male");
		optionGroup_2.addItem("Female");
		absoluteLayout_3.addComponent(optionGroup_2,
				"top:256.0px;bottom:125.0px;left:102.0px;");

		return absoluteLayout_3;
	}

	public String getNickname() {
		return Nickname.getValue();
	}

	public void setNickname(String nickname) {
		Nickname.setValue(nickname);
	}

	public String getLastnameInputBox() {
		return LastnameInputBox.getValue();
	}

	public void setLastnameInputBox(String lastName) {
		this.LastnameInputBox.setValue(lastName);
	}

	public String getFirsnameInputBox() {
		return firsnameInputBox.getValue();
	}

	public void setFirsnameInputBox(String firstName) {
		this.firsnameInputBox.setValue(firstName);
	}

	public String getEditFirsnameInputBox() {
		return textField_1.getValue();
	}

	public void setEditFirsnameInputBox(String firstName) {
		this.textField_1.setValue(firstName);
	}

	public String getEditLastnameInputBox() {
		return textField_2.getValue();
	}

	public void setEditLastnameInputBox(String LastName) {
		this.textField_2.setValue(LastName);
	}

	public String getEditNicknameInputBox() {
		return textField_3.getValue();
	}

	public void setEditNicknameInputBox(String nickname) {
		this.textField_3.setValue(nickname);
	}

	public String getEditNumberCellGroup() {
		return textField_4.getValue();
	}

	public void setEditNumberCellGroup(String cellGroup) {
		this.textField_4.setValue(cellGroup);
	}

	public String getEditNumberBsGroup() {
		return textField_5.getValue();
	}

	public void setEditNumberBsGroup(String bsGroup) {
		this.textField_5.setValue(bsGroup);
	}

	public String getEditNumberOneOnOne() {
		return textField_6.getValue();
	}

	public void setEditNumberOneOnOne(String oneOnOne) {
		this.textField_6.setValue(oneOnOne);
	}

	public String getEditMemberId() {
		return memberId_textBox.getValue();
	}

	public void setEditMemberId(String memberId) {
		this.memberId_textBox.setValue(memberId);
	}

	public void setClassfication(String classification) {
		this.comboBox_3.setValue(classification);
	}

	public void setLDICheckBox(Boolean check) {
		this.checkBox_2.setValue(check);
	}

	public void setSolCheckBox(Boolean check) {
		this.checkBox_3.setValue(check);
	}

	public void setGenderOption(String gender) {
		this.optionGroup_2.select(gender);
	}

	@Override
	public void enter(ViewChangeEvent event) {
		System.out.println("entered..");

	}

}
